moov-io/paygate

- internal/version/version.go
- main.go
- makefile
- pkg/achclient/client.go
- pkg/achclient/client_test.go
I'm unsure if we want to wrap this in a go-kit circuit breaker as inside k8s we only have the one endpoint.
Issue: https://github.com/moov-io/paygate/issues/8
> pkg/achclient: Add a quick proof of making requests over to ach service

- go.mod
- go.sum
- http.go
- main.go
- pkg/idempotent/idempotent.go
- pkg/idempotent/lru/lru.go
- pkg/idempotent/lru/lru_test.go
- transfers.go
- transfers_test.go
- vendor/github.com/hashicorp/golang-lru/.gitignore
- vendor/github.com/hashicorp/golang-lru/2q.go
- vendor/github.com/hashicorp/golang-lru/LICENSE
- vendor/github.com/hashicorp/golang-lru/README.md
- vendor/github.com/hashicorp/golang-lru/arc.go
- vendor/github.com/hashicorp/golang-lru/doc.go
- vendor/github.com/hashicorp/golang-lru/go.mod
- vendor/github.com/hashicorp/golang-lru/lru.go
- vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
- vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
- vendor/modules.txt
This adds a working implementation of handling X-Idempotency-Key and
does so for local dev / beta without any additional deployment.
I plan to add a redis implementation, but when we need it later on.
Fixes: #15
> http: add idempotency key checker, inmem LRU for now

- .travis.yml
The current master build is broken, but https://github.com/moov-io/ach/pull/324 fixed it for ach, so let's do the same here.
> ci: let windows fail and install gcc (for windows)

- Dockerfile
The container isn't able to access the data volume and fail to
boot. For now I'm reverting the "run as non-root user" change.
Issue: https://github.com/moov-io/infra/issues/25
> build: switch back to running as root

- database.go
- pkg/achclient/client.go
- pkg/achclient/client_test.go
- pkg/achclient/files.go
- pkg/achclient/files_test.go
- transfers.go
- transfers_test.go
We should delete the file to clean out space for other files. 
Issue: https://github.com/moov-io/api/issues/56
> transfers: delete ACH file when a transfer is deleted

- database.go
- depositories.go
> The depository owner's valid Customer ID or Originator ID
This field isn't needed as we store `user_id` on the sqlite table. That'll be used to search, not a field on the `Transfer` struct.
See: https://github.com/moov-io/api/pull/59
> depositories: drop Parent field

- main.go
- ofac.go
- ofac_test.go
We'll integrate proper health checks, but `panic`'ing on startup is an anti-pattern so let's get rid of that. 
Issue: https://github.com/moov-io/paygate/issues/50
> ping and log against ACH and OFAC rather than panic on startup

- renovate.json
It's annoying getting a PR per dependency, so let's group them all into one larger PR.
I still want to figure out why `go mod vendor` isn't ran, but that's another issue.
> renovate: set groupName to consolidate PR's

- README.md
- database.go
- depositories.go
- microDeposits.go
- microDeposits_test.go
Right now this information is only kept in logs, which makes any auditing infeasible.
> Save micro-deposit fileIds in database

- microDeposits.go
We'll likely need to keep these around, but they clutter up moov.io/demo when our apitest binary runs. Let's remove them right away for now.
> microDeposits: delete ACH files (for now)

- common.go
- common_test.go
math/big.Rat would sometimes have error rounding and thus ACH files were created $0.01 off, which is a major bug. Instead, let's handle amounts as int's in paygate and properly convert from their string values which we get in the HTTP api.
It might just make more sense to use an external library rather than our unique parsing code. (i.e. https://github.com/shopspring/decimal)
> common: convert Amount.number to int (always in cents)

- depositories_test.go
- main.go
- originators_test.go
- receivers_test.go
- transfers.go
- transfers_test.go
When there's a transfer moving funds between the same routing number we need to ensure the receiver's account exists in GL. (The originator is checked on Originator creation.) This helps ensure the account is valid. 
In a later PR we need to submit the transaction against GL prior to Transfer creation.
> transfers: check Receiver Depository exists in GL for transfers on the same RoutingNumber

- ofac.go
- ofac_test.go
I was seeing log lines like the following:
```
ts=2019-04-30T19:57:38.130155Z caller=ofac.go:174 customers="ofac: found SDN 11375 with match 0.00 (Jane Doe)" userId=0719d201c83bd7b856333cf498c8c83e89cf268f
```
This doesn't make sense and so we need to set the match percent (as paygate needs that for blocking) and log about it.
> ofac: search: set match percent on SDN if an AltName overrides it

- common.go
- common_test.go
- database.go
- depositories.go
- depositories_test.go
- file_transfer_async.go
- file_transfer_async_test.go
- openapi.yaml
- transfers.go
- transfers_test.go
This pull request introduces logic in paygate to parse and process returned ACH files. Typically these indicate an error and should mark the `Transfer` as such while also offering notification to the user about the error. 
Issue: https://github.com/moov-io/paygate/issues/90
> transfers: process returned files and update their status

- receivers.go
- receivers_test.go
This performs a basic format check on the provided email address and
strips out extra junk that RFC 5322 allows. (i.e. 'Bob <bob@example.com')
We don't validate the hostname or mailbox (by sending an activation
email) and I'm unsure if this should be done in a new service or
not. User signup needs to validate emails also, so it seems either
Auth should perform that task or it should be left up to another service.
> receivers: pass emails through net/mail.ParseAddress

- docs/ach.md
- file_transfer_async.go
I noticed the only mention of this is in logs, which aren't that easy to parse. We should expose this for faster/easier alerting to a human operator.
> files: add missing_ach_file_upload_configs for when configurations aren't found

- docs/local-dev.md
- file_transfer.go
- go.mod
- go.sum
- makefile
Previously I ran a long magic command to test out paygate's FTP logic. I've shipped a Docker image and bundled the command into `make start-ftp-server` that's easier to distribute. 
Also, I had to mess with (e)passive mode and I'm not completely sure which should be the default in production. I assume we'll have to make EPSV configurable in the future.
> build: add command for a local FTP server

- README.md
- file_transfer_async.go
- main.go
This allows paygate's async file operations to be disabled. Previously
paygate would just keep failing to connect to the local dev SFTP
endpoint or any configured ones.
> files: support 'off' to disable async file operations

- internal/database/mysql.go
- internal/database/sqlite.go
Noticed then when reading through https://github.com/writeas/writefreely/blob/v0.9.1/database-sqlite.go#L36-L50. They handle sqlite and mysql just like paygate.
> internal/database: check driver error types for unique violations

- README.md
- accounts.go
- accounts_test.go
- depositories.go
- depositories_test.go
- fed.go
- fed_test.go
- file_transfer_async.go
- file_transfer_async_test.go
- http.go
- http_test.go
- main.go
- microDeposits.go
- microDeposits_test.go
- ofac.go
- ofac_test.go
- pkg/achclient/client.go
- pkg/achclient/client_test.go
- pkg/achclient/mock_client.go
This allows private CA's to be added in for internal calls between
paygate and other services over TLS.
> http: setup http.Client's with additional root certificates

- README.md
- main.go
```
$ LOG_FORMAT=JSON HTTP_BIND_ADDRESS=:9999 go run . 
{"caller":"main.go:51","startup":"Starting paygate server version v0.6.0-dev","ts":"2019-07-06T23:00:12.628838Z"}
...
{"caller":"main.go:210","startup":"binding to :9999 for HTTP server","ts":"2019-07-06T23:00:12.805433Z"}
```
Fixes: https://github.com/moov-io/paygate/issues/158
> main: override -log.format with LOG_FORMAT and -http.addr with HTTP_BIND_ADDRESS

- README.md
"Deployment" is a bit confusing. "Getting Started" seems to be better for someone's first visit to the project.
> docs: trim up deploy steps and refer it as 'Getting Started'

- CHANGELOG.md
- README.md
- docs/ach.md
- file_transfer.go
- file_transfer_async.go
- file_transfer_async_test.go
- file_transfer_configs.go
- file_transfer_configs_test.go
- file_transfer_test.go
- internal/database/mysql.go
- internal/database/sqlite.go
SFTP is a different protocol (that we also need to support), so let's
call the existing implementation what it is -- FTP.
Issue: #173
> files: rename 'sftp' to 'ftp' as sftp is an ssh-based file transfer protocol

- README.md
- file_transfer.go
- file_transfer_test.go
- http_test.go
This allows private root CA's to be used with FTP connections.
Issue: #176
> files: support setting additional root certificates for FTP connections

- file_transfer_async_test.go
This was missed in one test which caused us to use paygate's root dir (rather than a temp dir) for clutterting of test files/dirs.
> files: set fileTransferController.rootDiir in all tests

- main.go
filepath.Dir returns '.' on an empty string (to represent the current dir) so our check needs to be aware of that
> main: if ACH_FILE_STORAGE_DIR is our zero value use ./storage/

- README.md
- docker-compose.yml
- file_transfer_async.go
This allows local dev installs to upload smaller files and if any FI has specific requirements. 
Issue: https://github.com/moov-io/paygate/issues/200
> files: read ACH_FILE_MAX_LINES to override NACHA 10k line default

- file_transfer_async_test.go
- internal/filetransfer/config.go
- internal/filetransfer/config_test.go
This config value allows paygate to switch between its local dev FTP and SFTP servers for quick testing of the async file retrieval and uploading.
While this is dev/testing code in production any deployment should override these with their own configuration for each FI.
> internal/filetransfer: add DEV_FILE_TRANSFER_TYPE for local dev

- docker-compose.yml
A few users have reported not seeing files in storage/merged/ which is
likely due to the default (10 minute) interval. Let's lower that in
local dev.
Issue: https://github.com/moov-io/paygate/issues/200
> build: in local dev merge and upload way more often

- internal/filetransfer/ftp.go
- internal/filetransfer/sftp.go
- internal/filetransfer/sftp_test.go
This fixes two bugs:
1. If the remote outbound directory doesn't exist, attempt to create it.
2. Upload files into the outbound directory, not the current dir.
Issue: https://github.com/moov-io/paygate/issues/170
> internal/filetransfer: sftp: create remote outbound dir and upload into it

- file_transfer_async.go
- file_transfer_async_test.go
- transfers.go
- transfers_test.go
ACH files are uploaded to their ODFI which passes them to the FED which passes them to the RDFI.
Fixes: https://github.com/moov-io/paygate/issues/204
> files: upload ACH files to their origin, not destination

- file_transfer_async.go
- file_transfer_async_test.go
- file_transfer_sync.go
- file_transfer_sync_test.go
- main.go
- transfers_test.go
This setup allows us to trigger the process for converting paygate Transfer objects into ACH files which are uploaded to their ODFI. Initially this is exposed over an admin HTTP endpoint.
Issue: https://github.com/moov-io/paygate/issues/200
> files: setup a channel for manually merge and upload of Transfers

- microDeposits.go
- microDeposits_test.go
- transfers.go
When we initiate micro deposits there are two credits against the external account and a debit which is the sum of both credits. This keeps the net balance unchanged so paygate doesn't need to require this third transaction to verify a Depository.
> micro-deposits: don't persist (and thus don't check) inversing debit

- main.go
- microDeposits.go
- microDeposits_test.go
This will be used by customer service to view the deposits made and
can be leveraged in testing to quickly read micro-deposit values.
Issue: https://github.com/moov-io/paygate/issues/213
> micro-deposits: add admin route for reading micro-deposits

- file_transfer_async.go
- file_transfer_async_test.go
- internal/filetransfer/file_transfer.go
This was reported by Ray as he noticed high CPU usage when paygate was
idle shortly after startup. A quick profile shows this looping was the
main cause as it didn't properly exit out in error conditions.
For now we're going to remove the errCount condition and just error
whenever a problem is encountered. If lower levels need retries then
we can add those on the lower level.
> files: drop cpu usage (infinite loop) in transfer merging for upload

- internal/filetransfer/file_transfer.go
- internal/filetransfer/file_transfer_test.go
Ran into during https://github.com/moov-io/paygate/pull/209
> internal/filetransfer: fix timezone issues in CutoffTime tests

- depositories.go
- depositories_test.go
- main.go
- microDeposits.go
- microDeposits_test.go
These methods were large and so let's trim them down with a common struct
> depositories: extract a struct for HTTP routes rather than large argument lists

- microDeposits.go
- microDeposits_test.go
- transfers.go
- transfers_ccd_test.go
- transfers_iat_test.go
- transfers_tel_test.go
- transfers_test.go
- transfers_web_test.go
When we send money to a remote account as a micro-deposit this money needs to come back to us (paygate's account). To do this we include a debit (to counteract the credit) from the remote account back to paygate's.
Issue: https://github.com/moov-io/paygate/issues/238
> micro-deposits: debit the micro-deposit from the remote account when crediting

- common.go
- common_test.go
- events_test.go
- microDeposits.go
- microDeposits_test.go
We need to balance micro-deposits made against a remote account, so accumulate those deposits for a final withdraw EntryDetail. Also, we will include the transactions in a single batch to optimize sending over the wire (in byte size and Fed cost).
Issue: https://github.com/moov-io/paygate/issues/244
> optimize micro-deposits in a Batch and withdraw deposits

- cmd/server/main.go
- file_transfer_async.go
- file_transfer_async_test.go
- file_transfer_sync.go
- file_transfer_sync_test.go
This change splits the admin endpoint for "flushing" files into two endpoints (and a third for doing both). The change allows operators to have fine grained control over where files are at any given moment. (Useful for tests and tutorials.)
Issue: https://github.com/moov-io/paygate/issues/239
> files: separate endpoints for flushing inbound and outbound files

- microDeposits.go
- microDeposits_test.go
This was missed before when adding the column, but we are recording it now.
> micro-deposits: record the transactionID when initiating

- internal/filetransfer/return.go
When processing a micro-deposit's EntryDetail return the Depository
won't be verified (as that's what micro-deposits are for).
When a Depository is found due to a return it might already be
Rejected (or in a non-Verified status) and so we should allow it to be
updated into Rejected.
Fixes: https://github.com/moov-io/paygate/issues/267
> internal/filetransfer: remove Depository Verified check in return processing

- internal/filetransfer/return.go
```
ts=2019-09-30T17:32:01.028945Z caller=return.go:41 processReturnFiles="processing return file return-WEB.ach from ASF APPLICATION SUPERVI (691000134)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x465d936]
goroutine 12 [running]:
github.com/moov-io/paygate/internal/filetransfer.(*Controller).processReturnEntry(0xc00020e0c0, 0x0, 0x0, 0x4909b4f, 0x1, 0x4909bd6, 0x2, 0xc000235264, 0x9, 0xc00023526e, ...)
/Users/adam/code/src/github.com/moov-io/paygate/internal/filetransfer/return.go:111 +0x4e6
github.com/moov-io/paygate/internal/filetransfer.(*Controller).processReturnFiles.func1(0xc000074310, 0x63, 0x4a28800, 0xc00008eea0, 0x0, 0x0, 0xe, 0xc0001cfa50) …
```
> internal/filetransfer: don't panic if micro-deposit Depository isn't found

- internal/filetransfer/incoming.go
- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
"incoming" refers more so to ACH files downloaded from the remote ODFI server and not an ACH file from Moov's ACH service.
> internal/filetransfer: rename loadIncomingFile to something better

- internal/filetransfer/return.go
- internal/filetransfer/returned_transfers.go
- internal/filetransfer/returned_transfers_test.go
We don't need to inspect the ACH File / EntryDetail to match a users
depositories against. Instead this information exists on the Transfer
that's already matched.
> internal/filetransfer: simplify Transfer returns Depository lookup

- cmd/server/main.go
- docs/ach.md
- internal/filetransfer/admin.go
- internal/filetransfer/admin_test.go
- internal/filetransfer/controller.go
- internal/filetransfer/controller_test.go
Often for testing it's helpful to hang until the file operations are completed (processing inbound and outboud files) rather than a fixed sleep and retry cycle.
Issue: https://github.com/moov-io/paygate/issues/276
> internal/filetransfer: allow synchronous waiting for flush routes

- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
Once we started allowing custom filenames we can't rely on the routing
number being part of the filename, so instead we have to inspect each
file's Header information.
Also, let's be consistent in using the destination routing number in
filenames when it is included.
> filetransfer: be better about mergable file discovery

- internal/filetransfer/config_test.go
- internal/filetransfer/controller.go
- internal/filetransfer/controller_test.go
- internal/filetransfer/incoming.go
- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
Previously we read all configs at startup, but then never refreshed those configs. Instead let's read whenever we need the config so updates in the database happen they are picked up.
> filetransfer: read configs from database rather than once at startup

- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
- internal/transfers.go
- internal/transfers_test.go
Outbound files should be named according to their destination routing
number as there will be multiple of those, but perhaps only one
origin.
All files are uploaded to the ODFI, but from there they're routed
based on the ach.FileHeader's ImmediateDestination. Let's name files
with the same logic.
> filetransfer: write filenames with their destination, not origin

- internal/database/mysql.go
- internal/database/sqlite.go
- internal/filetransfer/config.go
- internal/filetransfer/config_test.go
- internal/filetransfer/controller_test.go
- internal/filetransfer/file_transfer.go
- internal/filetransfer/ftp.go
- internal/filetransfer/ftp_test.go
- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
- internal/filetransfer/sftp.go
- internal/filetransfer/sftp_test.go
This change adds functionality into paygate to reject uploads if they don't match an optional IP/CIDR whitelist.
Docs: https://docs.moov.io/paygate/ach/#ip-whitelisting
Fixes: https://github.com/moov-io/paygate/issues/330
> filetransfer: reject file uploads if they're not whitelisted 

- README.md
- cmd/server/main.go
- internal/transfers/limits.go
- internal/transfers/limits_test.go
- internal/transfers/transfers.go
- internal/transfers/transfers_test.go
The check for a destination routing number is a bit harder to monitor as certain ABA's will have lots of transfers (big 5) and others will have small amounts. Let's re-think how to check this inside of paygate's hot code path of transfers. 
Fixes: https://github.com/moov-io/paygate/issues/383
> transfers: add one day limit, remove routing number check

- internal/model/address.go
- internal/model/originator.go
- internal/model/originator_test.go
- internal/model/receiver.go
- internal/model/receiver_test.go
- internal/originators/originators.go
- internal/receivers/receivers.go
Marshaling a zero-value `time.Time` is confusing, so we should return `null` instead.
> models: marshal null for BirthDate and Address if empty

- cmd/server/main.go
- internal/filetransfer/controller.go
- internal/filetransfer/controller_test.go
- internal/filetransfer/correction.go
- internal/filetransfer/correction_test.go
- internal/filetransfer/files.go
- internal/filetransfer/files_test.go
- internal/filetransfer/incoming.go
- internal/filetransfer/outgoing.go
- internal/filetransfer/outgoing_test.go
- internal/filetransfer/return.go
- internal/filetransfer/returned_micro_deposits.go
- internal/filetransfer/returned_micro_deposits_test.go
- internal/filetransfer/returned_transfers_test.go
- internal/transfers/cursor.go
- internal/transfers/mock_transfer_repo.go
- internal/transfers/repository.go
- internal/transfers/repository_test.go
This PR changes PayGate to mark Transfer objects as `processed` only when they're to be uploaded. We do this because a Transfer can be deleted prior to the upload and 
Fixes: https://github.com/moov-io/paygate/issues/439
> filetransfer: mark Transfers as Processed only immediately on upload

- internal/remoteach/files.go
- internal/transfers/transfers.go
- internal/transfers/transfers_test.go
Previously this check was shoved into `remoteach` (a package for http ACH operations) which is a completely wrong package for this check.
> transfers: refactor Receiver status check back into transfers package

- admin/README.md
- admin/api/openapi.yaml
- admin/api_admin.go
- admin/docs/AdminApi.md
- internal/filetransfer/admin.go
- internal/filetransfer/controller.go
- internal/filetransfer/outgoing.go
- openapi-admin.yaml
This endpoint is only for merging files. It won't upload outgoing files.
> filetransfer: add admin endpoint for merging outgoing files

- README.md
- cmd/server/main.go
- cmd/server/main_test.go
- internal/depository/router.go
- internal/depository/router_test.go
With options to disable Accounts and Customers we can offer a way to disable Fed calls. At least until something like #427 is implemented in PayGate. 
@wadearnold is this too dangerous to expose? Clients would need to understand the risk of returns (and their cost) from disabling this and sending invalid routing numbers.
> cmd/server: read env variable to disable Fed calls

- client/api/openapi.yaml
- client/api_transfers.go
- client/docs/TransfersApi.md
- internal/route/params.go
- internal/route/params_test.go
- internal/transfers/mock_transfer_repo.go
- internal/transfers/repository.go
- internal/transfers/repository_test.go
- internal/transfers/transfers.go
- internal/transfers/transfers_test.go
- internal/util/time.go
- internal/util/time_test.go
- openapi.yaml
Fixes: https://github.com/moov-io/paygate/issues/455
> transfers: read various filter params in http request 

- internal/database/mysql.go
- internal/transfers/limits.go
- internal/transfers/limits_test.go
Found this bug with MySQL where amounts are stored in too small of a column.
> database/mysql: expand transfers.amount column size

- internal/originators/originators.go
- internal/originators/originators_test.go
- internal/receivers/receivers.go
- internal/transfers/transfers.go
This error shows itself as returning "200 OK" in HTTP routes when
there's an underlying error. The error is logged, but the route does
not return an error.
The way this works is we call moovhttp.Prolbem(nil) which skips over
setting the status code to http.StatusBadRequest and any error
marshaling. Then the http.ResponseWriter will assume "200 OK" when the
response finishes.
> all: split 'err and object nil' checks into two blocks

- pkg/upload/ftp.go
- pkg/upload/ftp_test.go
- pkg/upload/sftp.go
- pkg/upload/sftp_test.go
It turns out we were encountering directories and downloading them as zero-length files, but assuming they were files. 
Fixes: https://github.com/moov-io/paygate/issues/494
> upload: setup FTP and SFTP tests for a directory inside inbound/returns

- examples/config.yaml
- go.mod
- go.sum
- pkg/config/pipeline.go
- pkg/transfers/pipeline/aggregate.go
- pkg/transfers/pipeline/notify/email.go
- pkg/transfers/pipeline/notify/email_test.go
- pkg/transfers/pipeline/notify/mailslurper_test.go
- pkg/transfers/pipeline/notify/multi.go
- pkg/transfers/pipeline/notify/notify.go
- pkg/transfers/pipeline/notify/pagerduty.go
- pkg/transfers/pipeline/notify/pagerduty_test.go
- pkg/transfers/pipeline/notify/slack.go
- pkg/transfers/pipeline/notify/slack_test.go
This will be used to send automated emails after an ACH file is uploaded or when an error occurs during upload.
> transfers/pipeline/notify: setup a basic email template

- docs/config.md
- go.sum
- pkg/config/pipeline.go
- pkg/config/pipeline_test.go
- pkg/transfers/pipeline/aggregate.go
- pkg/transfers/pipeline/audittrail/storage.go
- pkg/transfers/pipeline/audittrail/storage_blob.go
- pkg/transfers/pipeline/audittrail/storage_blob_test.go
- pkg/transfers/pipeline/audittrail/storage_mock.go
- pkg/transfers/pipeline/audittrail/storage_test.go
This allows storing (and encrypting) every uploaded file which is required by many agreements with an FI in production.
File retention after upload is not part of this storage.
> transfers/pipeline: add an audit trail storage interface

- docs/config.md
- pkg/transfers/inbound/cleanup_test.go
- pkg/transfers/inbound/download.go
- pkg/transfers/inbound/download_test.go
- pkg/transfers/inbound/mock_processor.go
- pkg/transfers/inbound/processor.go
- pkg/transfers/inbound/processor_test.go
- pkg/transfers/inbound/scheduler.go
- pkg/transfers/inbound/scheduler_test.go
I noticed with `storage.cleanup_local_directory: false` in the config the download directory is left unchanged. This was intended to keep **downloaded files**, but not empty directories. Let's cleanup those empty directories and keep files.
> transfers/inbound: cleanup empty dirs after download attempts

- api/openapi-admin.yaml
- pkg/admin/api_transfers.go
- pkg/admin/docs/TransfersApi.md
- pkg/transfers/admin/approval.go
- pkg/transfers/admin/approval_test.go
We should allow the workflow of requiring a review on a pending transfer.
> transfers/admin: allow status change of: Pending -> Reviewable

- cmd/server/main.go
- docs/config.md
- examples/config.yaml
- pkg/achx/files.go
- pkg/achx/files_test.go
- pkg/achx/ppd_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/odfi.go
- pkg/config/transfers.go
- pkg/config/transfers_test.go
- pkg/transfers/fundflow/first_party.go
- pkg/transfers/limiter/fixed.go
- pkg/transfers/limiter/fixed_test.go
- pkg/transfers/limiter/limiter.go
- pkg/transfers/router.go
- pkg/transfers/router_test.go
This is a change to support transfer limits in PayGate with an option to specify a different implementation. We use this currently with fixed amounts to reject transfers over a given dollar amount.
> transfers/limiter: add initial setup for rejecting Transfers by their Amounts

- docker-compose.yml
https://github.com/moov-io/paygate/issues/544
When using Docker on Windows, there are specific ports that are reserved and cannot be used when running applications within a container on Windows. This PR adjusts those ports to ports not in the reserved range so docker-compose up will work on a fresh checkout of the repo.
> change ports in docker-compose.yaml to allow for docker-compose up to work on windows

- pkg/transfers/mock_repository.go
- pkg/transfers/repository.go
- pkg/transfers/repository_test.go
- pkg/transfers/router.go
After we removed x-user-id it makes sense to just call it "get transfers."
> transfers: rename getUserTransfers to getTransfers

- pkg/transfers/router.go
This PR is a follow up to https://github.com/moov-io/paygate/issues/580. We need to set the `CompanyIdentification` if the organization has it configured or we use the default file based config.
> set companyid using org config as first option

- pkg/transfers/router.go
This PR returns a problem if the err is not nil when trying to look up the org config to get CompanyIdentification for a transfer.
> handle error on org config look up

- pkg/transfers/router.go
This PR removes a comment that's no longer needed when setting `companyID`
> remove comment

- pkg/transfers/pipeline/aggregate.go
This was reported by a community member where on shutdown the log is
filled with "FailedPrecondition" messages as this loop keeps iterating
until the underlying process is killed.
> transfers/pipeline: break out of async loop on Subscription shutdown

- docs/config.md
- examples/config.yaml
- pkg/config/odfi.go
- pkg/transfers/inbound/cleanup.go
- pkg/transfers/inbound/cleanup_test.go
- pkg/transfers/inbound/scheduler.go
- pkg/transfers/inbound/scheduler_test.go
This PR introduces logic to conditionally delete zero byte (empty) files that may exist on the remote server while a transfer is in place. We want to wait to delete these after a configurable amount of time.
> deleting empty files based on config

- docker-compose.yml
- examples/config.yaml
Fixes the commented out sftp example config to work when running along docker-compose.
> Fixing the example config to work with the docker-compose sftp container

- pkg/upload/sftp.go
Resolves on master
`ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group-exchange-sha256]"`
#625
> Add diffie-hellman-group-exchange-sha256 to resolve sftp handshake failed

- pkg/transfers/pipeline/aggregate.go
- x/schedule/cutoff.go
Example: 
```
ts=2021-02-11T00:04:00Z msg="starting 19:04 EST cutoff window processing" level=info package=main service=XferAggregator
ts=2021-02-11T00:04:00Z msg="wrote 0 files" level=info package=main
ts=2021-02-11T00:04:00Z msg="ended 19:04 EST cutoff window processing" level=info package=main service=XferAggregator
```
> schedule: include timezone in cutoff start/end logging

- pkg/transfers/inbound/processor.go
- pkg/transfers/inbound/processor_test.go
The `ProcessFile` function assumes all children of `downloadedFiles.dir` are directories. This PR no longer makes that assumption by checking if it is a file or dir and handling accordingly.
> Allowing processor to handle files downloaded to root of temp dir

- pkg/achx/batch.go
- pkg/achx/files.go
- pkg/transfers/fundflow/first_party.go
- pkg/transfers/fundflow/first_party_test.go
> transfers/fundflow: set EffectiveEntryDate for +2 days after last cutoff window

- docker-compose.kafka.yml
- examples/kafka.yaml
- pkg/stream/stream.go
- pkg/transfers/pipeline/publisher_kafka.go
- pkg/transfers/pipeline/subscription.go
PayGate Version: v0.10.2
What were you trying to do?
Add Kafka stream configuration.
What did you expect to see?
paygate to use the given kafka configuration without error
What did you see?
```
panic: ERROR setting up transfer subscription: unknown &config.StreamPipeline{InMem:(*config.InMemPipeline)(nil), Kafka:(*config.KafkaPipeline)(0xc000528f00)}
goroutine 1 [running]:
main.main()
/go/src/github.com/moov-io/paygate/cmd/server/main.go:116 +0x2097
```
How can we reproduce the problem?
the docker-compose file from the PR running paygate 0.10.2
> transfers/pipeline: fix kafka subscription
