moov-io/paygate

api/openapi.yaml
There are a few v1 endpoints left undefined still. This finishes out those definitions and does some cleanup of the existing spec. 
I'm going to finish spec'ing out the v1 endpoints before marking this non-WIP.
=> docs: finish (most) of the endpoint docs

Dockerfile
Issue: https://github.com/moov-io/infra/issues/25
=> docker: run as moov -- an unprivileged user

common.go, common_test.go, database.go, events.go, events_test.go, gateways.go, gateways_test.go, main.go, originators.go, originators_test.go, transfers.go, transfers_test.go
Fixes: https://github.com/moov-io/paygate/issues/6
=> events, gateways, originators, transfers: add sqlite persistence 

.travis.yml, common.go, customers.go, database.go, depositories.go, events.go, gateways.go, http.go, main.go, originators.go, pkg/achclient/client.go, pkg/achclient/client_test.go, transfers.go
Some projects are failing, but those aren't shown to our users.
=> ci: don't run misspell on vendor/, modernize config, fix megacheck errors, grab sqlite prometheus metrics

.gitignore, README.md, common.go, common_test.go, customers_test.go, depositories_test.go, gateways_test.go, http.go, http_test.go, makefile, originators_test.go, sqlite_test.go, transfers_test.go
This also adds `make cover-test` and `make cover-web` so you can get the HTML view easily.
See: https://blog.golang.org/cover
=> all: low hanging test coverage bump

common.go, customers.go, customers_test.go, depositories.go, depositories_test.go, main.go, originators.go, originators_test.go, transfers.go, transfers_test.go
Whenever these objects are created we need to ensure the `Depository` exists and belongs to the user. This prevents users from using depositories that aren't theirs.   
Part of https://github.com/moov-io/paygate/issues/8
=> Validate Depository on Customer, Originator, Transfer create

bin/transfer-setup.sh, common.go, database.go, depositories.go, depositories_test.go, microDeposits.go, microDeposits_test.go, transfers.go
Issue: https://github.com/moov-io/paygate/issues/22
=> Implement micro-deposit endpoints, mock values for now

customers.go, customers_test.go, depositories.go, depositories_test.go, gateways.go, go.mod, go.sum, microDeposits_test.go, originators.go, transfers.go, vendor/github.com/moov-io/base/.gitignore, vendor/github.com/moov-io/base/.travis.yml, vendor/github.com/moov-io/base/CODE_OF_CONDUCT.md, vendor/github.com/moov-io/base/CONTRIBUTING.md, vendor/github.com/moov-io/base/README.md, vendor/github.com/moov-io/base/doc.go, vendor/github.com/moov-io/base/go.mod, vendor/github.com/moov-io/base/time.go, vendor/github.com/moov-io/base/time.rb, vendor/modules.txt
Fixes: https://github.com/moov-io/paygate/issues/31
=>  all: convert to use github.com/moov-io/base Time

common.go, customers.go, depositories.go, gateways.go, main.go, microDeposits.go, microDeposits_test.go, originators.go, pkg/achclient/client_test.go, pkg/achclient/files.go, pkg/achclient/files_test.go, pkg/achclient/mock_client.go, transfers.go
micro-deposits are transfers which Moov (or whoever runs paygate) initiate to validate a Depository. To do this we'll need to start a few transfers, so this works towards that logic in paygate. 
Issue: https://github.com/moov-io/paygate/issues/30
=> microDeposits: create ACH files for each small deposit

depositories.go, main.go, microDeposits_test.go, originators.go, originators_test.go
Had this change locally for a bit and it's helped debug some problems.
=> all: add log lines for errors in HTTP routes

.travis.yml, openapi.yaml, transfers.go, transfers_iat.go, transfers_iat_test.go, transfers_ppd.go
Issue: https://github.com/moov-io/paygate/issues/84
=> transfers: create IAT batches (with a couple of mocked fields)

openapi.yaml, transfers.go, transfers_iat.go, transfers_web.go, transfers_web_test.go
Issue: https://github.com/moov-io/paygate/issues/91
=> transfers: support building WEB batches (some fields hardcoded)

openapi.yaml
Issue: https://github.com/moov-io/go-client/issues/15
=> api: inline parameters to fix codegen crash

depositories.go, events.go, file_transfer_async.go, microDeposits.go, originators.go, receivers.go, transfers.go
Also fix missed Customer -> Receiver rename
=> all: return database/sql Rows.Err where applicable

depositories.go, depositories_test.go
I noticed we didn't require validation again after changing the AccountNumber or RoutingNumber, which we need to do (via micro-deposits) to prevent subtle changes that would withdraw funds from an account the user wasn't authorized to access.
=> depositories: require validation again after AccountNumber or RoutingNumber is upserted

README.md
Just adding dependencies for building from source to the readme.
=> Build from source readme updates

file_transfer_async.go, file_transfer_async_test.go, main.go
Issue: https://github.com/moov-io/paygate/issues/127
=> files: test fileTransferRepository with mysql

README.md, main.go, transfers.go
Not all customers need to integrate with a general ledger solution, so we should allow these to be disabled.
Issue: https://github.com/moov-io/paygate/issues/126
=> transfers: add config for disabling Accounts integration

openapi.yaml, transfers.go, transfers_tel.go, transfers_tel_test.go, transfers_test.go, transfers_web.go
This PR adds support for creating `TEL` ach batches. 
cc @wadearnold @bkmoovio 
Issue: https://github.com/moov-io/paygate/issues/92
=>  transfers: support TEL ACH transfers

accounts.go, accounts_test.go, file_transfer_async.go, file_transfer_async_test.go, go.mod, go.sum, main.go, transfers.go, transfers_test.go
Issue: https://github.com/moov-io/paygate/issues/131
=> files: reverse a Transfer's transaction when the ACH file has been returned

openapi.yaml, transfers.go, transfers_ccd.go, transfers_ccd_test.go
Issue: https://github.com/moov-io/paygate/issues/135
=> transfers: support CCD and the required Addenda05 on them

file_transfer_async.go, file_transfer_async_test.go
Also, support `R05` for [CCD transfers](https://github.com/moov-io/paygate/issues/135).
=> files: test updateTransferFromReturnCode 

.travis.yml, README.md, docker-compose.yml, makefile
Big thanks to Taylor Gunnoe for writing up the initial file in his blog post.
https://medium.com/@tgunnoe/3586757e45d6
=> build: include a docker-compose setup

file_transfer_async.go, file_transfer_async_test.go, file_transfer_configs.go, file_transfer_configs_test.go, go.mod, go.sum, main.go
Issue: https://github.com/moov-io/paygate/issues/147
=> file-transfers: add (admin) HTTP endpoints for reading configs

transfers_ccd.go, transfers_ppd.go, transfers_tel.go, transfers_web.go
This is an optional field that can be presented to the user (either in
statements or on a transaction), so let's populate this field too.
See: https://github.com/moov-io/ach/pull/558#issuecomment-505648969
=> transfers: set CompanyDescriptiveDate to today

internal/database/mysql.go
Fixes: https://github.com/moov-io/paygate/issues/156
=> internal/database: fix confusing log from copy/paste

depositories.go, depositories_test.go
Fixes: https://github.com/moov-io/paygate/issues/159
=> depositories: fix bug where multiple fields weren't updated

transfers_tel_test.go, transfers_web_test.go
Just verifying the errors returned match what we expect. 
Issue: https://github.com/moov-io/paygate/issues/164
=> transfers: verify TEL and WEB reoccurring transfers are rejected

transfers.go
This PR at least partially addresses this issue:
https://github.com/moov-io/paygate/issues/164
By making this change I am able to create a transfer with WEBDetail.  However, I have no idea yet if this is a full or proper fix.  I've also never done a PR here so I could be doing this all wrong...
=> change asTransfer to copy option sub-structs

README.md, main.go
I got the idea from https://github.com/moov-io/ach/pull/573 and after https://github.com/moov-io/paygate/pull/162
=> main: override -admin.addr with HTTP_ADMIN_BIND_ADDRESS

transfers.go, transfers_ccd_test.go, transfers_iat_test.go, transfers_tel_test.go, transfers_test.go, transfers_web_test.go
Issue: https://github.com/moov-io/paygate/issues/164
=> transfers: ship YYYDetail sub-objects as pointers to copy around properly

internal/database/mysql.go, internal/database/sqlite.go, internal/filetransfer/config.go, internal/filetransfer/config_test.go, internal/filetransfer/sftp.go, internal/filetransfer/sftp_test.go
Misc cleanup from https://github.com/moov-io/paygate/issues/170 when we added SFTP support.
=> internal/filetransfer: sftp: override HostKeyCallback if provided in config

internal/filetransfer/ftp.go
ChangeDirToParent only works if we're moving one level deeper at a time (for inbound or return) so instead let's capture the current dir and move back to that after each command.
=> internal/filetransfer: ftp: change back to the previous working dir after changing

file_transfer_async.go
Our FTPTransferAgent can't handle concurrent requests like this as we change directories in some commands (and thus some need that state).
We should look into if our FTPTransferAgent can operate from the root directory.
=> files: stop reading and downloading files concurrently

internal/filetransfer/sftp.go
This error appears without any real consistency, but a simple retry
seems to work. This might break down at higher concurrency levels, but
for now let's try this.
I tried adding/removing ciphers and key exchange protocols in the
ssh.Config, but nothing gave me 100% success. Reading the
sftp.InternalInconsistency (error) documentation states:
> // InternalInconsistency indicates the packets sent and the data queued to be
> // written to the file don't match up. It is an unusual error and usually is
> // caused by bad behavior server side or connection issues. The error is
> // limited in scope to the call where it happened
Our SFTP server is just an image from GitHub with stars and some
updates this year, but I wouldn't call it a production ready image.
See: …
=> internal/filetransfer: retry file reads on "internal inconsistency" errors

go.mod, go.sum, internal/database/database.go, internal/database/mysql.go, internal/database/mysql_test.go, internal/database/sqlite.go, internal/database/sqlite_test.go
This does create a `migrations` table in sqlite or mysql.
=> internal/database: use lopezator/migrator for versioned database migrations

docs/ach.md, internal/filetransfer/sftp.go, internal/filetransfer/sftp_test.go
Fixes: https://github.com/moov-io/paygate/issues/182
=> internal/filetransfer: sftp: read base64 encoded public/private keys

README.md, main.go
Fixes: https://github.com/moov-io/paygate/issues/195
=> main: bind HTTP server with TLS if HTTPS_* variables are defined

common.go, common_test.go
Issue: https://github.com/moov-io/paygate/issues/202
=> common: return strconv.Atoi's error when parsing whole dollar amount

internal/filetransfer/sftp.go, internal/filetransfer/sftp_test.go
Reported by @rayjlinden, thanks!
=> internal/filetransfer: sftp: fix nil panic in readFiles

README.md, accounts_test.go, depositories.go, depositories_test.go, go.mod, go.sum, main.go, main_test.go, microDeposits.go, microDeposits_test.go, receivers.go, transfers.go, transfers_test.go
Issue: https://github.com/moov-io/paygate/issues/141
=> micro-deposits: un-hardcode amounts and post the transaction to Accounts

depositories.go, depositories_test.go, file_transfer_async.go, file_transfer_async_test.go, internal/database/mysql.go, internal/database/sqlite.go, microDeposits.go, microDeposits_test.go, receivers.go, transfers.go
Issue: https://github.com/moov-io/paygate/issues/150
=> micro-deposits: add to ACH files for upload to their ODFI

file_transfer_async.go, internal/filetransfer/file_transfer.go, internal/filetransfer/sftp.go, internal/filetransfer/sftp_test.go, transfers.go
People will likely miss this log, but it's something.
=> internal/filetransfer: sftp: log once (in app lifetime) about missing host_public_key 

.travis.yml, docker-compose.yml, makefile
Original changes from https://github.com/moov-io/paygate/pull/210
=> build: update docker images (for tests) and download tools instead

depositories.go, microDeposits.go
Debugging a couple pull requests (see: https://github.com/moov-io/paygate/pull/210) led me down a path here to make the logging around Depository objects better.
=> depositories: improve logging

.travis.yml
Issue: https://github.com/moov-io/infra/issues/58
=> build: download gocyclo instead of installing it

microDeposits.go, microDeposits_test.go
=> micro-deposits: 404 if we don't find the Depository during init

common.go, common_test.go, microDeposits.go, microDeposits_test.go
* Fixed an issue in Amount.Equal()
* Slightly refactored SQLDepositoryRepo.confirmMicroDeposits()
* Rewrote the unit tests for both functions
@adamdecaf
=> confirmMicroDeposits Fix

client/api/openapi.yaml, client/api_depositories.go, client/api_events.go, client/api_gateways.go, client/api_originators.go, client/api_receivers.go, client/api_transfers.go, client/docs/DepositoriesApi.md, client/docs/EventsApi.md, client/docs/GatewaysApi.md, client/docs/OriginatorsApi.md, client/docs/ReceiversApi.md, client/docs/TransfersApi.md, openapi.yaml
Issue: https://github.com/moov-io/fed/issues/69
=> api,client: require x-user-id HTTP header in OpenAPI spec

cmd/server/main.go, internal/depositories.go, internal/depositories_test.go, internal/microDeposits_test.go, internal/ofac/client.go, internal/ofac/client_test.go, internal/ofac/mock_client.go, internal/originators.go, internal/originators_test.go, internal/receivers.go, internal/receivers_test.go
More refactoring to cleanup paygate where I can quickly.
=> internal/ofac: move client into separate package

go.mod, go.sum, internal/file_transfer_sync_test.go, internal/filetransfer/config_test.go, internal/filetransfer/ftp_test.go, internal/microdeposit/admin_test.go, internal/util/timeout.go, internal/util/timeout_test.go, internal/util/util_test.go
I'm trying to fix the sporadic CI failures due to base/admin.Server not binding correctly.
=> all: upgrade github.com/moov-io/base to v0.11.0-rc1

internal/filetransfer/config.go, internal/filetransfer/config_test.go
Fixes: https://github.com/moov-io/paygate/issues/147
=> internal/filetransfer: implement upsert and delete for file transfer config

cmd/server/main.go, internal/depositories.go, internal/depositories_test.go, internal/filetransfer/async.go, internal/filetransfer/async_test.go, internal/filetransfer/sync.go, internal/filetransfer/sync_test.go, internal/microDeposits.go, internal/microDeposits_test.go, internal/mock_depository_repo.go, internal/mock_transfer_repo.go, internal/originators.go, internal/originators_test.go, internal/receivers_test.go, internal/transfers.go, internal/transfers_test.go
I need to keep rafactoring these giant files into smaller ones, so
this is a step that has to be done.
=> all: move file_transfer_[a]sync.go to internal/filetransfer sub-package

cmd/server/main.go
This was missed from earlier this morning. Reported by Ray
=> cmd/server: wait to shutdown filetransfer.Controller until paygate quits

internal/transfers.go
This issue was reported by Ray regarding same day transfers, but the
logic applies as Transfers could be created on a weekend and not
posted for a day or two (which could push outside of the window).
Also, if a transfer is created today paygate sets the
EffectiveEntryDate to tomorrow in some cases and thus if the file is
immediately returned would fall outside of today's window.
=> transfers: expand window for EffectiveEntryDate comparison against created_at

internal/filetransfer/return.go, internal/filetransfer/returned_transfers.go, internal/filetransfer/returned_transfers_test.go
Since micro-deposits are originated via our ODFIAccount there won't be an originating Depository like with Transfer (returns) and instead we just need to match the receiving Depository.
=> internal/filetransfer: micro-deposit returns only need one (Receiver) Depository 

internal/accounts.go, internal/depositories.go, internal/filetransfer/controller.go, internal/filetransfer/sftp.go, internal/microDeposits.go, internal/receivers.go, internal/transfers.go
From golangci-lint in https://github.com/moov-io/paygate/pull/246
=> all: misc linter fixup

internal/filetransfer/admin.go, internal/filetransfer/controller.go
Issue: https://github.com/moov-io/paygate/issues/242
=> internal/filetransfer: pass through x-request-id and x-user-id HTTP headers

cmd/server/main.go, docs/ach.md, docs/admin-endpoints.md, internal/database/mysql.go, internal/database/sqlite.go, internal/filetransfer/config.go, internal/filetransfer/config_test.go, internal/filetransfer/controller.go, internal/filetransfer/controller_test.go, internal/filetransfer/file_transfer.go, internal/filetransfer/filename_template.go, internal/filetransfer/filename_template_test.go, internal/filetransfer/incoming.go, internal/filetransfer/outgoing.go, internal/filetransfer/outgoing_test.go
Issue: https://github.com/moov-io/paygate/issues/172
=> internal/filetransfer: setup more formal ACH filename templating

internal/ofac/client_test.go
Inspired by https://github.com/moov-io/paygate/pull/289
=> ofac: use v0.11.1 in tests

internal/filetransfer/file_transfer.go, internal/filetransfer/file_transfer_test.go, internal/filetransfer/outgoing.go
=> filetransfer: add Config helper for getting the proper outbound filename template

internal/filetransfer/outgoing.go
This prevents flushing files when the cutoff_times table is missing a
row for the routing number.
=> filetransfer: remove wasteful cutoff time lookup

cmd/server/main.go, cmd/server/main_test.go, internal/accounts.go, internal/fed/client.go, internal/fed/client_test.go, internal/ofac/client.go, pkg/achclient/client.go, pkg/achclient/client_test.go, pkg/achclient/mock_client.go
Part of the larger setup in https://github.com/moov-io/paygate/pull/299 which needs broken apart.
=> all: pass through endpoint params to client constructors

go.mod, go.sum, internal/customers/client.go, internal/customers/client_test.go, internal/customers/test_client.go, internal/transfers.go, internal/transfers_test.go
Issue: https://github.com/moov-io/paygate/issues/98
=> transfers: check Disclaimers for each Customer before allowing a transfer

go.mod, go.sum, internal/filetransfer/correction.go, internal/filetransfer/correction_test.go
Issue: https://github.com/moov-io/paygate/issues/315
=> filetransfer: update Depository and Originator/Receiver objects from incoming COR entries

internal/depositories.go, internal/depositories_test.go, internal/depository/admin.go, internal/depository/admin_test.go, internal/mock_depository_repo.go
Issue: https://github.com/moov-io/paygate/issues/279
=> depositories: add admin route for overriding status

go.mod, go.sum, internal/customers/client_test.go
the bot force pushed on its PR
=> chore(deps): update all

internal/customers/cursor.go, internal/customers/cursor_test.go, internal/database/mysql.go, internal/database/sqlite.go, internal/depositories.go, internal/depository_migration.go, internal/depository_migration_test.go, internal/events/repository.go, internal/gateways/storage.go, internal/micro_deposit_attempts.go, internal/micro_deposits.go, internal/receivers.go, internal/refresh_ofac.go, internal/refresh_ofac_test.go
It appears paygate has connection leaks so we need to run through connections and verify/close them. I got the idea for checking this from the link below.
Idea: https://redd.it/4j5ysh
=> internal/database: check all connections are closed prior to test close

admin/api/openapi.yaml, admin/api_admin.go, admin/docs/AdminApi.md, admin/docs/FileTransferConfig.md, admin/model_file_transfer_config.go, internal/database/mysql.go, internal/database/sqlite.go, internal/filetransfer/config.go, internal/filetransfer/config_test.go, openapi-admin.yaml
noticed when working on https://github.com/moov-io/paygate/pull/361
=> filetransfer: fix partial updating of FileTransferConfig in admin HTTP routes

README.md, internal/database/mysql.go, internal/database/sqlite.go, internal/http.go, internal/http_test.go, internal/transfers.go
Issue: https://github.com/moov-io/paygate/issues/364
=> transfers: store the client's real ip address on creation

internal/accounts/accounts.go, internal/accounts/client.go, internal/accounts/mock_client.go, internal/depository/micro_deposits.go, internal/depository/micro_deposits_test.go, internal/originators/originators_test.go, internal/transfers/transactions.go, internal/transfers/transactions_test.go
Issue: https://github.com/moov-io/paygate/issues/386
=> accounts: return an internal interface rather than moov-io/accounts models

internal/customers/client.go, internal/customers/client_test.go, internal/customers/customers.go, internal/customers/test_client.go, internal/ofac/refresh_test.go, internal/transfers/customers_test.go
Issue: https://github.com/moov-io/paygate/issues/386
=> customers: create an interface, don't leak moovcustomers

.travis.yml, internal/filetransfer/sftp_test.go, makefile
Fixes: https://github.com/moov-io/paygate/issues/421
=> build: release windows binaries

client/api/openapi.yaml, client/api_transfers.go, client/docs/TransfersApi.md, openapi.yaml
Fixes: https://github.com/moov-io/paygate/issues/426
=> api: properly document endpoint return from validating files from a transfer

cmd/server/main.go, internal/filetransfer/controller.go, internal/filetransfer/controller_test.go, internal/filetransfer/files_test.go, internal/filetransfer/outgoing.go, internal/filetransfer/outgoing_test.go, internal/filetransfer/removal.go, internal/filetransfer/removal_test.go, internal/transfers/files_test.go, internal/transfers/mock_transfer_repo.go, internal/transfers/repository.go, internal/transfers/transfers.go, pkg/achclient/files_test.go, pkg/achclient/mock_client.go
Issue: https://github.com/moov-io/paygate/issues/439
=> filetransfer: remove pending Transfers from files prior to upload

cmd/server/main.go, internal/depository/router.go, internal/filetransfer/controller.go, internal/filetransfer/controller_test.go, internal/filetransfer/removal.go, internal/filetransfer/removal_test.go, internal/transfers/transfers.go
Issue: https://github.com/moov-io/paygate/issues/442
=> filetransfer: remove micro-deposits from mergable files on Depository deletion 

internal/achx/doc.go, internal/achx/trace.go, internal/achx/trace_test.go, internal/filetransfer/create_returns.go, internal/filetransfer/prenote.go, internal/remoteach/ccd.go, internal/remoteach/files.go, internal/remoteach/files_test.go, internal/remoteach/iat.go, internal/remoteach/ppd.go, internal/remoteach/tel.go, internal/remoteach/web.go
Follow up from https://github.com/moov-io/paygate/pull/448
=> filetransfer: set additional fields on EntryDetails prior to return

internal/database/mysql.go, internal/database/sqlite.go, internal/filetransfer/correction.go, internal/filetransfer/returned_transfers.go, internal/filetransfer/returned_transfers_test.go, internal/model/transfer.go, internal/model/transfer_test.go, internal/transfers/approval_test.go, internal/transfers/repository_test.go, openapi.yaml
Replace `reclaimed` with `failed`. 
Fixes: https://github.com/moov-io/paygate/issues/459
=> Remove reclaimed transfer status

client/api/openapi.yaml, client/api_originators.go, client/api_receivers.go, client/docs/OriginatorsApi.md, client/docs/ReceiversApi.md, internal/originators/mock_repository.go, internal/originators/originators.go, internal/originators/originators_test.go, internal/originators/repository.go, internal/originators/repository_test.go, openapi.yaml
Fixes: https://github.com/moov-io/paygate/issues/476
=> originators: handle updating an originator over HTTP

client/api/openapi.yaml, client/api_transfers.go, client/docs/TransfersApi.md, internal/transfers/repository.go, internal/transfers/transfers.go, internal/transfers/transfers_test.go, openapi.yaml
Issue: https://github.com/moov-io/paygate/issues/456
=> transfers: add 'status' query param to filter Transfers

admin/README.md, admin/api/openapi.yaml, admin/api_admin.go, admin/docs/AdminApi.md, internal/depository/admin.go, internal/depository/depository_admin.go, internal/depository/depository_admin_test.go, internal/transfers/admin.go, internal/transfers/approval.go, internal/transfers/approval_test.go, internal/transfers/mock_transfer_repo.go, internal/transfers/repository.go, openapi-admin.yaml
Fixes: https://github.com/moov-io/paygate/issues/457
=> depository,transfer: drop redundant /users/{userID} from admin paths

.github/workflows/codeql.yaml
From GitHub Satellite today (https://githubsatellite.com/). 
Instructions: https://github.com/github/codeql-action
=> build: add codeql github action

README.md, docker-compose.yml, examples/config.yaml, examples/getting-started.sh, examples/micro-deposit-setup.sh, examples/micro-deposits.sh
Demo: https://github.com/adamdecaf/paygate/tree/examples#getting-started
=> examples: setup transfer and micro-deposit scripts on the README

docs/README.md, docs/metrics.md, docs/production.md
Starting a page around the expectations and requirements for running PayGate in production.
=> docs: add a "Production Checklist" page

pkg/transfers/repository.go, pkg/transfers/repository_test.go
Fixes: https://github.com/moov-io/paygate/issues/462
=> transfers: only delete transfers in PENDING status

api/openapi.yaml, pkg/client/docs/MicroDeposits.md, pkg/client/docs/Transfer.md, pkg/client/model_micro_deposits.go, pkg/client/model_transfer.go, pkg/database/mysql.go, pkg/database/sqlite.go, pkg/transfers/pipeline/repository.go, pkg/transfers/pipeline/repository_test.go, pkg/transfers/repository.go, pkg/validation/microdeposits/repository.go
Fixes: https://github.com/moov-io/paygate/issues/542
=> transfers: record processedAt when file is uploaded to ODFI

api/openapi.yaml, pkg/client/docs/MicroDeposits.md, pkg/client/docs/Transfer.md, pkg/client/model_micro_deposits.go, pkg/client/model_transfer.go, pkg/database/mysql.go, pkg/transfers/repository.go, pkg/validation/microdeposits/repository.go
Found when looking at endpoint responses. Similar to https://github.com/moov-io/customers/pull/106
=> api,client: marshal null returnCode, not zero-value model

CONTRIBUTING.md, README.md
@adamdecaf please, check updates.
=> Update example commands in readme

pkg/transfers/router.go, pkg/transfers/router_test.go
Found when looking at https://github.com/moov-io/app/pull/55
=> transfers: validate amount.value better

api/admin.yaml, api/client.yaml, pkg/client/api/openapi.yaml, pkg/client/api_transfers.go, pkg/client/docs/TransfersApi.md, pkg/transfers/repository.go, pkg/transfers/repository_test.go, pkg/transfers/router.go, pkg/transfers/router_test.go
=> fix: add ability to filter transfers by customerIDs query param

.github/workflows/examples.yml, examples/common/common.go
After https://github.com/moov-io/paygate/pull/598 we can add CI to the "Getting Started" guide to verify it works long term.
=> examples: add CI for getting-started guide

api/client.yaml, go.sum, pkg/client/README.md, pkg/client/api/openapi.yaml, pkg/client/api_configuration.go, pkg/client/docs/ConfigurationApi.md, pkg/client/docs/OrganizationConfiguration.md, pkg/client/model_organization_configuration.go, pkg/organization/mock_repository.go, pkg/organization/repository.go, pkg/organization/router.go, pkg/organization/router_test.go
See https://github.com/moovfinancial/engineering-guide/pull/34 for more of a reason on this change. My bad for not noticing it in the original PR
=> organization: use full name in public model

api/client.yaml, pkg/client/api/openapi.yaml, pkg/client/api_configuration.go, pkg/client/api_transfers.go, pkg/client/api_validation.go
@joshsadler asked about this today. We didn't specify it in our docs.
=> api,client: include 412 "precondition failed" from idempotency key checks

pkg/transfers/pipeline/notify/pagerduty.go, pkg/transfers/pipeline/notify/slack.go, pkg/transfers/pipeline/notify/slack_test.go
This helps to clearly state what happened.
=> transfers/pipeline/notify: capitalize Slack and PagerDuty action status

README.md
Added a Google Cloud Run Button
=> Update README.md to be able to Run on Google Cloud
